class CENAPI {
    constructor(
        diferencidor,
        solicitudId,
        numeroControl,
        oficioSolicitud,
        expediente,
        SPA,
        estatusExpediente,
        fechaInicioExpediente,
        tipoExpediente,
        fechaHoraRecepcion,
        fechaHoraAsignacionInicial,
        fechaHoraAsignacionFinal,
        elementoId,
        nombreElemento,
        reasignacion,
        productoSolicitadoId,
        tipoProductoSolicitado,
        tipoSolicitud,
        unidad,
        procedencia,
        region,
        estatusSolicitud,
        fechaCumplimiento,
        fechaEstatusExpediente,
        conSinDetenido,
        estatusValidacion,
        entidadFederativa,
        autoridadRequiriente
    ) {
        (this.diferencidor = diferencidor),
        (this.solicitudId = solicitudId),
        (this.numeroControl = numeroControl),
        (this.oficioSolicitud = oficioSolicitud),
        (this.expediente = expediente),
        (this.SPA = SPA),
        (this.estatusExpediente = estatusExpediente),
        (this.fechaInicioExpediente = fechaInicioExpediente),
        (this.tipoExpediente = tipoExpediente),
        (this.fechaHoraRecepcion = fechaHoraRecepcion),
        (this.fechaHoraAsignacionInicial = fechaHoraAsignacionInicial),
        (this.fechaHoraAsignacionFinal = fechaHoraAsignacionFinal),
        (this.elementoId = elementoId),
        (this.nombreElemento = nombreElemento),
        (this.reasignacion = reasignacion),
        (this.productoSolicitadoId = productoSolicitadoId),
        (this.tipoProductoSolicitado = tipoProductoSolicitado),
        (this.tipoSolicitud = tipoSolicitud),
        (this.unidad = unidad),
        (this.procedencia = procedencia),
        (this.region = region),
        (this.estatusSolicitud = estatusSolicitud),
        (this.fechaCumplimiento = fechaCumplimiento),
        (this.fechaEstatusExpediente = fechaEstatusExpediente),
        (this.conSinDetenido = conSinDetenido),
        (this.estatusValidacion = estatusValidacion),
        (this.entidadFederativa = entidadFederativa),
        (this.autoridadRequiriente = autoridadRequiriente);
    }
}

class CGSP {
    constructor(
        solicitudId,
        expediente,
        SPA,
        estatusExpediente,
        fechaInicioExpediente,
        estatusSolicitud,
        tipoExpediente,
        fechaHoraSolicitud,
        elementoId,
        especialidad,
        fechaHoraAsignacionInicial,
        fechaHoraAsignacionFinal,
        unidad,
        region,
        productoId,
        tipoProducto,
        procedencia,
        fechaProducto,
        fechaEstatusExpediente,
        conSinDetenido,
        oficioSolicitud,
        folioEstatal,
        anoFolioEstatal,
        nombreElemento,
        direccionGeneral,
        estatusValidacion,
        fechaHoraAcuse,
        entidadFederativa
    ) {
        (this.solicitudId = solicitudId),
        (this.expediente = expediente),
        (this.SPA = SPA),
        (this.estatusExpediente = estatusExpediente),
        (this.fechaInicioExpediente = fechaInicioExpediente),
        (this.estatusSolicitud = estatusSolicitud),
        (this.tipoExpediente = tipoExpediente),
        (this.fechaHoraSolicitud = fechaHoraSolicitud),
        (this.elementoId = elementoId),
        (this.especialidad = especialidad),
        (this.fechaHoraAsignacionInicial = fechaHoraAsignacionInicial),
        (this.fechaHoraAsignacionFinal = fechaHoraAsignacionFinal),
        (this.unidad = unidad),
        (this.region = region),
        (this.productoId = productoId),
        (this.tipoProducto = tipoProducto),
        (this.procedencia = procedencia),
        (this.fechaProducto = fechaProducto),
        (this.fechaEstatusExpediente = fechaEstatusExpediente),
        (this.conSinDetenido = conSinDetenido),
        (this.oficioSolicitud = oficioSolicitud),
        (this.folioEstatal = folioEstatal),
        (this.anoFolioEstatal = anoFolioEstatal),
        (this.nombreElemento = nombreElemento),
        (this.direccionGeneral = direccionGeneral),
        (this.estatusValidacion = estatusValidacion),
        (this.fechaHoraAcuse = fechaHoraAcuse),
        (this.entidadFederativa = entidadFederativa);
    }
}

class PFM_MM {
    constructor(
        diferencidor,
        actoId,
        solicitudId,
        expediente,
        SPA,
        fechaOficio,
        fechaHoraRecepcion,
        fechaHoraAsignacionInicial,
        fechaHoraAsignacionFinal,
        elementoId,
        tipoSolicitud,
        clasificacion,
        unidad,
        subUnidad,
        region,
        entidadFederativa,
        estatusSolicitud,
        actoInvestigacion,
        fechaActoInvestigacion,
        estatusExpediente,
        fechaCumplimiento,
        fechaInicioExpediente,
        fechaEstatusExpediente,
        oficioSolicitud,
        nombreElemento,
        numeroControl,
        anoNumeroControl,
        nombreAutoridad,
        estatusValidacion,
        conSinDetenido,
        reasignacion
    ) {
        (this.diferencidor = diferencidor),
        (this.actoId = actoId),
        (this.solicitudId = solicitudId),
        (this.expediente = expediente),
        (this.SPA = SPA),
        (this.fechaOficio = fechaOficio),
        (this.fechaHoraRecepcion = fechaHoraRecepcion),
        (this.fechaHoraAsignacionInicial = fechaHoraAsignacionInicial),
        (this.fechaHoraAsignacionFinal = fechaHoraAsignacionFinal),
        (this.elementoId = elementoId),
        (this.tipoSolicitud = tipoSolicitud),
        (this.clasificacion = clasificacion),
        (this.unidad = unidad),
        (this.subUnidad = subUnidad),
        (this.region = region),
        (this.entidadFederativa = entidadFederativa),
        (this.estatusSolicitud = estatusSolicitud),
        (this.actoInvestigacion = actoInvestigacion),
        (this.fechaActoInvestigacion = fechaActoInvestigacion),
        (this.estatusExpediente = estatusExpediente),
        (this.fechaCumplimiento = fechaCumplimiento),
        (this.fechaInicioExpediente = fechaInicioExpediente),
        (this.fechaEstatusExpediente = fechaEstatusExpediente),
        (this.oficioSolicitud = oficioSolicitud),
        (this.nombreElemento = nombreElemento),
        (this.numeroControl = numeroControl),
        (this.anoNumeroControl = anoNumeroControl),
        (this.nombreAutoridad = nombreAutoridad),
        (this.estatusValidacion = estatusValidacion),
        (this.conSinDetenido = conSinDetenido),
        (this.reasignacion = reasignacion);
    }
}

class PFM_MJ {
    constructor(
        actoId,
        solicitudId,
        SPA,
        expediente,
        fechaLibramiento,
        fechaPrescripcion,
        fechaHoraRecepcion,
        fechaHoraAsignacionInicial,
        fechaHoraAsignacionFinal,
        elementoId,
        clase,
        clasificacion,
        unidad,
        subUnidad,
        region,
        origenSolicitud,
        entidadFederativa,
        estatusSolicitud,
        fechaEstatusSolicitud,
        actoInvestigacion,
        estatusExpediente,
        fechaInicioExpediente,
        fechaEstatusExpediente,
        juzgado,
        expedienteJuzgado,
        oficioSolicitud,
        nombreAutoridad,
        nombreElemento,
        numeroControl,
        anoNumeroControl,
        estatusValidacion,
        conSinDetenido,
        reasignacion
    ) {
        (this.actoId = actoId),
        (this.solicitudId = solicitudId),
        (this.SPA = SPA),
        (this.expediente = expediente),
        (this.fechaLibramiento = fechaLibramiento),
        (this.fechaPrescripcion = fechaPrescripcion),
        (this.fechaHoraRecepcion = fechaHoraRecepcion),
        (this.fechaHoraAsignacionInicial = fechaHoraAsignacionInicial),
        (this.fechaHoraAsignacionFinal = fechaHoraAsignacionFinal),
        (this.elementoId = elementoId),
        (this.clase = clase),
        (this.clasificacion = clasificacion),
        (this.unidad = unidad),
        (this.subUnidad = subUnidad),
        (this.region = region),
        (this.origenSolicitud = origenSolicitud),
        (this.entidadFederativa = entidadFederativa),
        (this.estatusSolicitud = estatusSolicitud),
        (this.fechaEstatusSolicitud = fechaEstatusSolicitud),
        (this.actoInvestigacion = actoInvestigacion),
        (this.estatusExpediente = estatusExpediente),
        (this.fechaInicioExpediente = fechaInicioExpediente),
        (this.fechaEstatusExpediente = fechaEstatusExpediente),
        (this.juzgado = juzgado),
        (this.expedienteJuzgado = expedienteJuzgado),
        (this.oficioSolicitud = oficioSolicitud),
        (this.nombreAutoridad = nombreAutoridad),
        (this.nombreElemento = nombreElemento),
        (this.numeroControl = numeroControl),
        (this.anoNumeroControl = anoNumeroControl),
        (this.estatusValidacion = estatusValidacion),
        (this.conSinDetenido = conSinDetenido),
        (this.reasignacion = reasignacion);
    }
}

module.exports = {
    CENAPI: CENAPI,
    CGSP: CGSP,
    PFM_MM: PFM_MM,
    PFM_MJ: PFM_MJ
};